import numpy as np


def random_su_d_dev(d: int, norm: bool = True, seed: int | None = None) -> np.ndarray:
    """
    Generates a random su(d) matrix, assuming the hermitian and traceless properties of
    the su(d) algebra. The matrix is generated by creating a random complex matrix,
    symmetrizing it to make it hermitian, and then subtracting the trace to make it
    traceless.

    Args:
        d (int): Dimension of the su(d) matrix.
        norm (bool): Whether to normalize the matrix to have a Frobenius norm of 1.
                Default is True.
        seed (int | None): Seed for the random number generator. Default is None.

    Returns:
        np.ndarray: A random su(d) matrix of shape (d, d).
    """
    rng = np.random.default_rng(seed)
    A = rng.normal(size=(d, d)) + 1j * rng.normal(size=(d, d))

    # Makes hermitian
    H = (A + A.conj().T) / 2

    # Makes traceless
    H = H - np.trace(H) / d * np.eye(d)

    if norm:
        H = H / np.linalg.norm(H, ord=2)

    return H


def random_diagonal_dev(
    d: int, norm: bool = True, seed: int | None = None
) -> np.ndarray:
    """
    Generates a random su(d) matrix, in a diagonal form, assuming the hermitian and
    traceless properties of the su(d) algebra.

    Args:
        d (int): Dimension of the su(d) matrix.
        norm (bool): Whether to normalize the matrix to have a Frobenius norm of 1.
            Default is True.
        seed (int | None): Seed for the random number generator. Default is None.

    Returns:
        np.ndarray: A random su(d) matrix of shape (d, d).
    """
    rng = np.random.default_rng(seed)
    H = np.diag(rng.normal(size=d))

    if norm:
        H = H / np.linalg.norm(H, ord=2)

    return H


def random_su_d(
    d: int, norm: bool = True, seed: int | None = None, diag: bool = False
) -> np.ndarray:
    """
    Generates a random su(d) matrix, assuming the hermitian and traceless properties of
        the su(d) algebra.

    Args:
        d (int): Dimension of the su(d) matrix.
        norm (bool): Whether to normalize the matrix to have a Frobenius norm of 1.
            Default is True.
        seed (int | None): Seed for the random number generator. Default is None.
        diag (bool): Whether to generate a diagonal su(d) matrix. Default is False.

    Returns:
        np.ndarray: A random su(d) matrix of shape (d, d).
    """
    if diag:
        return random_diagonal_dev(d, norm=norm, seed=seed)
    else:
        return random_su_d_dev(d, norm=norm, seed=seed)
