"""
----------------------------------------------------------------------------------------
Author: Henrique Ennes (https://hlovisiennes.github.io/)
----------------------------------------------------------------------------------------
Utils functions for the Vartrotter package.
----------------------------------------------------------------------------------------
Utils:
    get_commutator
    get_commutators_from_list
    adjoint
    random_su_d
"""

import numpy as np

"""
----------------------------------------------------------------------------------------
Basic linear algebra
----------------------------------------------------------------------------------------
"""


def get_commutator(A: np.ndarray, B: np.ndarray) -> np.ndarray:
    """
    Computes the commutator of two matrices A and B.

    Args:
        A (np.ndarray): First matrix.
        B (np.ndarray): Second matrix.

    Returns:
        np.ndarray: The commutator [A, B] = AB - BA.
    """
    return 1j * (A @ B - B @ A)


def get_commutators_from_list(
    matrices: list[np.ndarray], indices: bool = False
) -> np.ndarray:
    """
    Computes the commutators of a list of matrices.

    Args:
        matrices (list[np.ndarray]): List of matrices to compute the commutators.
        indices (bool): If True, yields the indices of the matrices along with the
            commutator. Default is False.
    Returns:
        np.ndarray: A generator object of commutators of the input matrices.
    """
    # Taking the generators like this avoids repetition of commutators,
    # since [A, B] = -[B, A]
    for i, A in enumerate(matrices):
        for j in range(i + 1, len(matrices)):
            B = matrices[j]

            if indices:
                yield i, j, get_commutator(A, B)
            else:
                yield get_commutator(A, B)


def adjoint(U: np.ndarray, X: np.ndarray) -> np.ndarray:
    """
    Computes the adjoint action of a unitary matrix U on a matrix X.

    Args:
        U (np.ndarray): Unitary matrix.
        X (np.ndarray): Matrix to be transformed.

    Returns:
        np.ndarray: The result of the adjoint action U X U^dagger.
    """
    return U @ X @ U.conj().T


"""
----------------------------------------------------------------------------------------
Generate random martices in su(d)
----------------------------------------------------------------------------------------
"""


def random_su_d_dev(
    d: int, norm: float | None = np.pi, seed: int | None = None
) -> np.ndarray:
    """
    Generates a random su(d) matrix, assuming the hermitian and traceless properties of
        the su(d) algebra.
    The matrix is generated by creating a random complex matrix, symmetrizing it to
        make it hermitian, and then subtracting the trace to make it traceless.

    Args:
        d (int): Dimension of the su(d) matrix.
        norm (float | None): Normalize the matrix to have a given operator norm.
            Default is pi. If None, does not normalize.
        seed (int | None): Seed for the random number generator. Default is None.

    Returns:
        np.ndarray: A random su(d) matrix of shape (d, d).
    """
    rng = np.random.default_rng(seed)
    A = rng.normal(size=(d, d)) + 1j * rng.normal(size=(d, d))

    # Makes hermitian
    H = (A + A.conj().T) / 2

    # Makes traceless
    H = H - np.trace(H) / d * np.eye(d)

    if norm is not None:
        H = H * norm / np.linalg.norm(H, ord=2)

    return H


def random_diagonal_dev(
    d: int, norm: float | None = np.pi, seed: int | None = None
) -> np.ndarray:
    """
    Generates a random su(d) matrix, in a diagonal form, assuming the hermitian and
        traceless properties of the su(d) algebra.

    Args:
        d (int): Dimension of the su(d) matrix.
        norm (float | None): Normalize the matrix to have a given operator norm.
            Default is pi. If None, does not normalize.
        seed (int | None): Seed for the random number generator. Default is None.

    Returns:
        np.ndarray: A random su(d) matrix of shape (d, d).
    """
    rng = np.random.default_rng(seed)
    H = np.diag(rng.normal(size=d))

    if norm is not None:
        H = H * norm / np.linalg.norm(H, ord=2)

    return H


def random_su_d(
    d: int, norm: float | None = np.pi, seed: int | None = None, diag: bool = False
) -> np.ndarray:
    """
    Generates a random su(d) matrix, assuming the hermitian and traceless properties of
        the su(d) algebra.

    Args:
        d (int): Dimension of the su(d) matrix.
        norm (float | None): Normalize the matrix to have a given operator norm.
            Default is pi. If None, does not normalize.
        seed (int | None): Seed for the random number generator. Default is None.
        diag (bool): Whether to generate a diagonal su(d) matrix. Default is False.

    Returns:
        np.ndarray: A random su(d) matrix of shape (d, d).
    """
    if diag:
        return random_diagonal_dev(d, norm=norm, seed=seed)
    else:
        return random_su_d_dev(d, norm=norm, seed=seed)
